### ISSUE TITLE
MS0101 create the main qt project with an interface similar to the one in opensim-gui.

### ISSUE THREAD

**Issue by idhamari** [VisSimKoblenz/opensimQt#1]
create the main interface with only the exit function.
The current toolbar should be a main toolbar that can have different groups based on a selection in Window menu.

Add new Window menu item: Toolbars
 this item should have different toolbar groups e.g. 

- Common: Open,Save,Reload,Plot ..
- Simulation: Simulate, Stop, Motion,  
- Tools:InverseKenimatics, InverseDynamics

**Comment by idhamari** [comment]
@yasseerr two notes:
1. it is better to organize things as we may have many files later. 
2. Please use CMake, this makes it easier to manage cross-platform applications.

I added a draft from my old uncomplete work. It is tested on Linux. I think the only function works is a new model that loads an STL file to the vtk widget.

**Comment by yasseerr** [comment]
@idhamari  hi!
1. as for organizing the project  i will try to follow the existing structure of the OpenSimGui , except where there is no similarities .
2. i started the project using qmake because ithought it support all platform (code less deploy every where) and it  is more suitable with qt , but you are right maybe someone will try and build it using VS even though the project gonna be installed using an qt installer, so i m gonna try and suitch the project build to cmake 
 3. here is the initial UI  till this commit from the GUI-Features branch if you want clone it and see if you have any suggestion or objection befor merging to master
https://github.com/VisSimKoblenz/opensimQt/commit/b736a2dbb246a7832d79320897c43457a3467320
![2020-02-06_18-08-50](https://user-images.githubusercontent.com/37770658/73962916-9a487b80-490f-11ea-9fdf-e8744f846e31.png)

4. thank you for the draft contribution i will try and integrate it afterword

**Comment by idhamari** [comment]
It looks great, well done! There are a few comments but it is better if we check them later when we have some functionality.
For now, please integrate the CMake file from the draft and use your suggested structure. After that merge to master and close this issue.

**Comment by yasseerr** [comment]
Done ! 
project restructured and using Cmake
