### ISSUE TITLE
  MS0203_01: Complete MissingStuff

### ISSUE THREAD

**Issue by idhamari** [VisSimKoblenz/opensimQt#22]
* [x] two-ways communication between the navigator and the visualizer:
      - when selecting an object in the navigator it should be selected in the visualizer (if possible) 
* [x] Coordinates tab.
      - similar to the one in the java interface.

**Comment by yasseerr** [comment]
@idhamari  Hi!
1. the coordinate tab it has been implemented except for the poses(working on it) as in this video [URL](https://drive.google.com/file/d/1h46g4FWiBvmwN3ITk_CFjNKHph6S-WuU/view?usp=sharing) 

2.for the two way comuniation they are already linked exept the musclees (related to the open bug) like when you click on the object in the scene it will be selected in the navigator. or do you want also change the color of the vtk actor when (clicked/doubleclicked) from the navigator?. and for the wrap object bug i think i'm gonna try and solve it because i encountered a similar one in the coordinates so mybe they are the same.

**Comment by idhamari** [comment]
@yasseerr 

Well done, I just checked it and it seems to work :watermelon: 

> do you want also change the color of the vtk actor when (clicked/doubleclicked) from the navigator?. 

yes , this is the expected behavior. The color in the visualizer should be changed as well. Also if the user clicked again (in the navigator or the visualizer) on the same object, the selection should be removed.

**Comment by yasseerr** [comment]
Hello @idhamari 
1- the two way communication is now implemented (select-deselect actors from the navigator and the visualizer)
2- the size of the coordinates widget will now expend when selected 
give it a test when you find time to check if something is missing

**Comment by idhamari** [comment]
well done :watermelon: 

This task is now closed!
