### ISSUE TITLE
MS0400_T01 Building the required tools

### ISSUE THREAD

**Issue by idhamari** [VisSimKoblenz/opensimQt#23]
This should not take longer than one week, the deadline is  27/7/2020 

In this task, you prepare your environment for development by building, installing (note it is strongly recommended you use the same versions):

* CMake 3.14.4
* Python 3.6.9
* Qt 5.9.5 Qt Creator 4.5.2 (build should include all libraries used in the current project)
* opensim-core 4.2
* Netbeans 8.2, Java 1.8.0
* opensim-gui
* [vtk-9.0r3](https://github.com/Kitware/VTK/tree/v9.0.0.rc3).
* our opensimQt
* [pythonQt](https://github.com/MeVisLab/pythonqt)

After the build test if everything works by loading some models and running some simulations

If you have a problem please post here and we will try to help. When you complete the build we will have an online meeting to check that everything is ok.

**Comment by riteshsv** [comment]
would it be ok to install higher versions ?

**Comment by idhamari** [comment]
I have Ubuntu 18.04 and that what works for me. You can try something else but It may not work. If you like we can have an online skype to do this together on Tuesday or Wednesday.

**Comment by idhamari** [comment]
Here are some tips:

- we first build opensim dependencies, this should create an installation folder which should be added to the system path.
- we then build opensim-core (usually I build without the wrapping first to check if everything is ok then I add the wrapping and rebuild again). This should create another installation folder that should be added to the system path.
- Finally, we build opensim-gui. First we open opensim project in netbeans then close. After that we use the script to build opensim-gui which usually copy files from opensim-core installation folder then we open opensim project in netbeans again and build it. Most of the error I faced are related to a missing path or incompatible version.

**Comment by idhamari** [comment]
@riteshsv how is the progress so far?  do you need help?

**Comment by riteshsv** [comment]
I worked till late night yesterday. I was able to run OpenSim java. Today I
will complete the installation of openSim Qt along the vtk.

**Comment by idhamari** [comment]
@riteshsv  Excellent job :watermelon:  please let me know when you complete so we can do the testing together and close this issue.

**Comment by riteshsv** [comment]
I was having OpenGL version issues while running openSimQt. My vtk build was messed up. Building vtk again and then check.

**Comment by idhamari** [comment]
I think the recent VTK versions required recent OpenGL which probably dependant on the graphics card.

**Comment by riteshsv** [comment]
I found the issue. It is because QVTKOpenGLNativeWidget extends QOpenGLWidget. QOpenGLWidget wants to create the OpenGL context and manage windows for which it uses QSurfaceFormat. I found in the documentation of QVTKOpenGLNativeWidget. Typical usage is:
// before initializing QApplication, set the default surface format.
QSurfaceFormat::setDefaultFormat(QVTKOpenGLNativeWidget::defaultFormat());

so currently i have modifed the code like this:
`int main(int argc, char *argv[])
{

#ifdef \_\_APPLE\_\_
    QSurfaceFormat::setDefaultFormat(QVTKOpenGLNativeWidget::defaultFormat());                              //To create appropria window and OpenGL context.
#endif`


And it has worked well. Below is the extract from documentation:

@class QVTKOpenGLNativeWidget
 * @brief QOpenGLWidget subclass to house a vtkGenericOpenGLRenderWindow in a Qt
 * application.
 *
 * QVTKOpenGLNativeWidget extends QOpenGLWidget to make it work with a
 * vtkGenericOpenGLRenderWindow.
 *
 * Please note that QVTKOpenGLNativeWidget only works with vtkGenericOpenGLRenderWindow.
 * This is necessary since QOpenGLWidget wants to take over the window management as
 * well as the OpenGL context creation. Getting that to work reliably with
 * vtkXRenderWindow or vtkWin32RenderWindow (and other platform specific
 * vtkRenderWindow subclasses) was tricky and fraught with issues.
 *
 * Since QVTKOpenGLNativeWidget uses QOpenGLWidget to create the OpenGL context,
 * it uses QSurfaceFormat (set using `QOpenGLWidget::setFormat` or
 * `QSurfaceFormat::setDefaultFormat`) to create appropriate window and context.
 * You can use `QVTKOpenGLNativeWidget::copyToFormat` to obtain a QSurfaceFormat
 * appropriate for a vtkRenderWindow.
 *
 * A typical usage for QVTKOpenGLNativeWidget is as follows:
 * @code{.cpp}
 *
 *  // before initializing QApplication, set the default surface format.
 *  QSurfaceFormat::setDefaultFormat(QVTKOpenGLNativeWidget::defaultFormat());
 *
 *  vtkNew<vtkGenericOpenGLRenderWindow> window;
 *  QPointer<QVTKOpenGLNativeWidget> widget = new QVTKOpenGLNativeWidget(...);
 *  widget->SetRenderWindow(window.Get());
 *
 *  // If using any of the standard view e.g. vtkContextView, then
 *  // you can do the following.
 *  vtkNew<vtkContextView> view;
 *  view->SetRenderWindow(window.Get());
 *
 *  // You can continue to use `window` as a regular vtkRenderWindow
 *  // including adding renderers, actors etc.

**Comment by idhamari** [comment]
Well done :watermelon:  shall we close this issue?

**Comment by riteshsv** [comment]
The Geometry is not loading and I tried to set OPENSIM_HOME to opensim-gui/opensim-models as it will documented in Geometry.cpp and also i tried to add it to the PATH.

**Comment by riteshsv** [comment]
I have installed pythonQt also

**Comment by riteshsv** [comment]
I am closing the issue.

**Comment by idhamari** [comment]
@riteshsv 

> The Geometry is not loading and I tried to set OPENSIM_HOME to opensim-gui/opensim-models as it will documented in Geometry.cpp and also i tried to add it to the PATH.

We are using a modified version of the visualizer interface from somebody in opensimQt so the path should be defined the same way. For now you can add the path manually [here](https://github.com/VisSimKoblenz/opensimQt/blob/7f380b34a76c26c49ddb14fce7d03769bc269225/Gui/vsWidgets/vsMainWindow.cpp#L70) then rebuild. This should be simpler when we implement the preferences menu. 

We will also try to automate the build using scripts for Windows, Linux and Mac.
