### ISSUE TITLE
JV00 Build and run opensim gui 

### ISSUE THREAD

**Issue by idhamari** [VisSimKoblenz/opensimQt#9]
opensim-visualiser is not working in the gui

**Comment by idhamari** [comment]
issue is opened to in opensim-gui repository.

**Comment by yasseerr** [comment]
the visualiser is working 
the problem is that the previous installation of netbeans was somehow corrupted (system variables)
reinstalling with the latest update fixed the problem
![2020-01-26_22-13-34](https://user-images.githubusercontent.com/37770658/73141989-0adad700-408a-11ea-83bf-ca9f4bb2ee20.png)

**Comment by yasseerr** [comment]
however the bash script  didnt execute the last step 
here is the log
![2020-01-26_22-15-21](https://user-images.githubusercontent.com/37770658/73142076-019e3a00-408b-11ea-9179-fe5249b49353.png)

is it necessary to build the distribution ?

**Comment by idhamari** [comment]
Well done! please notice that we can use issues in our opensim-gui so the communication should be there. Here is [the milestone](https://github.com/VisSimKoblenz/opensim-gui/milestone/1)
